language: r
cache: packages

r:
  - oldrel
  - release
  - devel

r_packages:
  - covr
  - rmarkdown
  

notifications:
  email:
    on_success: change
    on_failure: change

## Code coverage
after_success:
  - Rscript -e 'covr::codecov()'
