language: r
cache: packages

r:
  - oldrel
  - release
  - devel

r_packages:
  - covr
  - rmarkdown
  
#needed for travis to be able to install the rgl package
#which is a dependency I think of BAT
before_install:
   - apt-get install libglu1-mesa-dev


notifications:
  email:
    on_success: change
    on_failure: change

## Code coverage
after_success:
  - Rscript -e 'covr::codecov()'
