language: r
cache: packages

r:
  - oldrel
  - release
  - devel

r_packages:
  - covr
  - rmarkdown
  
#needed for travis to be able to install the rgl package
#which is a dependency I think of BAT
addons:
  apt:
    packages:
      - libgdal-dev
      - libproj-dev

before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install libcgal-dev libglu1-mesa-dev mesa-common-dev; fi



notifications:
  email:
    on_success: change
    on_failure: change

## Code coverage
after_success:
  - Rscript -e 'covr::codecov()'
