#https://blog.jdblischak.com/posts/circleci-for-r-1/
#NOT_CRAN true should mean all tests run, including skip on cran
version: 2
jobs:
  build:
    docker:
      - image: rocker/verse:latest
        environment:
          NOT_CRAN: true
    steps:
      - checkout
      - run:
          name: Install package dependencies
          command: | 
            R -e 'install.packages("tinytex")'
            R -e 'tinytex::install_tinytex(extra_packages = "ec")'
            R -e 'install.packages("remotes")'
            R -e 'remotes::install_deps(dependencies = TRUE)'
      - run:
          name: Build package
          command: R CMD build .
      - run:
          name: Devtools check package
          command: R -e 'devtools::check()'
      - run:
          name: Check package
          command: R CMD check *tar.gz --no-manual
      - run:
          name: Calculate code coverage
          command: Rscript -e 'covr::codecov()'
          